### ISSUE TITLE
Should return long_description & division

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-ideas-api#12]
Need to include `long_description` and `division` in the Idea view.

**Comment by allthesignals** [comment]
Not sure what was happening with feature in #9 - Dokku behaves weirdly when changing config variables... maybe because I didn't have the config variable defined at all, I had to do a full rebuild. Anyway, this is showing in the API.

Note: If a field is blank, Airtable will just exclude the field attribute from the object, so be careful with iterating on fields that usually arrays.
